# Generated by Django 6.0.2 on 2026-03-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('owner', 'Owner'), ('player', 'Player')], default='player', max_length=10),
        ),
    ]
