# Generated by Django 6.0.2 on 2026-03-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turf', '0002_turf_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='turf',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
